-- Run this in your Supabase SQL Editor to create the necessary table for Animuse.

-- 1. Guild Configs (Pre-existing)
create table if not exists public.guild_configs (
  guild_id text primary key,
  welcome_channel_id text,
  logs_channel_id text,
  gallery_channel_ids text[],
  xp_enabled boolean default true,
  muse_role_id text,
  mafia_channel_id text
);

-- 2. Users (New)
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  user_id text not null,
  guild_id text not null,
  xp bigint default 0,
  level integer default 0,
  last_message timestamp with time zone default now(),
  constraint users_guild_user_key unique (user_id, guild_id)
);

-- Turn on Row Level Security (Standard Practice)
alter table public.guild_configs enable row level security;
alter table public.users enable row level security;

-- Policies for Service Role (Bot)
create policy "Enable all access for service role on configs"
on public.guild_configs for all using (true) with check (true);

create policy "Enable all access for service role on users"
on public.users for all using (true) with check (true);
