-- 1. Add suggestions_channel_id to guild_configs
alter table public.guild_configs 
add column if not exists suggestions_channel_id text;

-- 2. Create Suggestions Table
create table if not exists public.suggestions (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  user_id text not null,
  title text not null,
  content text not null,
  status text not null default 'pending',
  message_id text,
  channel_id text,
  thread_id text,
  upvotes integer default 0,
  downvotes integer default 0,
  created_at timestamp with time zone default now()
);

-- 3. Create Suggestion Votes Table (To prevent double voting)
create table if not exists public.suggestion_votes (
  suggestion_id bigint references public.suggestions(id) on delete cascade,
  user_id text not null,
  vote_type text not null check (vote_type in ('up', 'down')),
  primary key (suggestion_id, user_id)
);

-- 4. Enable RLS
alter table public.suggestions enable row level security;
alter table public.suggestion_votes enable row level security;

-- 5. Policies for Service Role
create policy "Enable all access for service role on suggestions"
on public.suggestions for all to service_role using (true) with check (true);

create policy "Enable all access for service role on suggestion_votes"
on public.suggestion_votes for all to service_role using (true) with check (true);
